name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: purescript-contrib/setup-purescript@main

#      - uses: actions/setup-node@v2
#        with:
#          node-version: "14.x"

      - name: Build the project
        run: spago build

      - name: Run tests
        run: spago test
